name: predator-prey-rl
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - matplotlib=3.7.1
  - pytorch::pytorch=2.1.0
  - pytorch::cpuonly
  - pip:
    - gymnasium==0.29.1
    - pygame==2.5.2
    - stable-baselines3==2.2.1
    - pillow==10.0.0
